name: Daily Job Scrape

on:
  schedule:
    # Runs at 12:30 UTC every day (8:30 AM EDT).
    - cron: '30 12 * * *'
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run the job scraper script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        run: python -m src.main

      - name: Upload Excel Report as Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Daily-Job-Report
          path: data/raw/NEW_jobs_report_*.xlsx
